# Generated by Django 3.2.3 on 2021-05-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identificationnumber',
            field=models.IntegerField(verbose_name=12),
        ),
    ]
