# Generated by Django 3.2.3 on 2021-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profileuser',
            fields=[
                ('idProfileuser', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
