# Generated by Django 3.2.3 on 2021-05-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Systemuser',
            fields=[
                ('idSystemuser', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('idnumber', models.IntegerField(verbose_name=12)),
            ],
        ),
    ]
