# Generated by Django 3.2.3 on 2021-05-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judicialtitle',
            fields=[
                ('idJudicialtitle', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name=30)),
                ('providencedate', models.DateField()),
                ('applicant', models.CharField(max_length=50)),
                ('defendant', models.CharField(max_length=50)),
                ('titlevalue', models.IntegerField(verbose_name=20)),
                ('tradenumber', models.IntegerField(verbose_name=30)),
                ('processfilingnumber', models.IntegerField(verbose_name=30)),
            ],
        ),
    ]
